name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

#    - name: Release APK Publisher
#      # You may pin to the exact commit or the version.
#      # uses: nightcrawler-/action-release-apk@2e64ff4ed716a67973753941590155abaeb07e7d
#      uses: nightcrawler-/action-release-apk@1.0.2
#      #with:
#        # Github secret token to allow automated publishing of APK to release.
#        #GITHUB_TOKEN: # optional
          
